### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by purplecofe** [t047771919/Gimmatek#1]
你的第一個commit版本在se上view顯示不出來，剛裝機過後這版本ＯＫ了

第一版我主要是加了collectionview的flowlayoutdelegate跟implement sizeforitemat才正常

你可以回到第一版run在se的模擬器跑看看

**Comment by t047771919** [comment]
好！謝謝您，第一版忘了測試不同尺寸的手機了所以沒注意到抱歉
請問還有哪邊需要修改呢？

**Comment by purplecofe** [comment]
基本上就這樣吧

**Comment by t047771919** [comment]
好 謝謝您，辛苦了!
